services:
  release_server:
    container_name: remotelab_server_release
    ports:
      - "8080:8080"
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro 
    device_cgroup_rules:
      - 'c 188:* rmw'
    build:
      context: .
      dockerfile: Dockerfile
      target: release_server
  release_gui:
    container_name: remotelab_gui_release
    ports:
      - "80:5000"
    build:
      context: .
      dockerfile: Dockerfile
      target: release_gui

